### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by debevv** [huww98/TimeChart#17]
Hi, does the library support hover tooltips? I'm asking because I read this line in the readme:
> name (string): The name of the series. Will be shown in legend and tooltips.

but I don't see any tooltip on mouse hover. Is there any non-documented option to enable them maybe?

Thanks in advance

**Comment by huww98** [comment]
No, tooltips is still on the to-do list. thanks for your interest.

**Comment by huww98** [comment]
Basic tooltip support is added. Also, users can build their own tooltip plugin.
