### ISSUE TITLE
scatter/event plot

### ISSUE THREAD

**Issue by MarineChap** [huww98/TimeChart#25]
Dear, 
 
_Sorry for the context I am a total newbie in this language. I am taking back a project from a colleague using this to display two signals in our web app (thanks for your work here)._ 

I would like to display specific events on top of the chart with specific markers. A scatter plot would do it equivalently I think. 
Do you have a way to display a scatter plot ? Or could give me some hints on where to look for it ? 

Also, being able to add a title to the figure would be nice as well. 

Thanks for your help.

**Comment by huww98** [comment]
Scatter plot is not implemented now. But I think you can easily implement one with the new (currently unreleased) plugin system. Basically, you can use https://github.com/huww98/TimeChart/blob/845c4e3eede96f3cf3e0df682afdc820436887d9/src/core/renderModel.ts#L137 this function to calculate where to draw the event markers. Then draw them with SVG.

https://github.com/huww98/TimeChart/blob/845c4e3eede96f3cf3e0df682afdc820436887d9/src/plugins/nearestPoint.ts This plugin also draw markers with SVG. maybe you can follow it.

As for the title, Why not just add it with HTML outside of the chart.

**Comment by MarineChap** [comment]
Super. Thanks for the tip. When do you think (roughly) you plan to release the plugin system ? Do you plan also to document the way to create plugins/add them from outside your code or it is something very current in this language and I should just google it ? 

As for the title, yes I am sure that is possible in HTML but I feel like it is something missing in the CreateChart method. However, that was just a user suggestion, and I will definitely add it myself via HTML. :)

Have a good day

**Comment by huww98** [comment]
I'm working on the document. Once I finished the doc, I will create a beta release. Maybe in a day or two.

**Comment by MarineChap** [comment]
Perfect ! Thank you so much. :) 

Have a good day.

**Comment by huww98** [comment]
Hi, please have a look at [this doc](https://huww98.github.io/TimeChart/docs/authoring_plugins). And I have published a [beta version](https://www.npmjs.com/package/timechart/v/1.0.0-beta.1). Feel free to ask if you have any confusion. I'm not a native English speaker. I have tried my best but maybe the doc is not very accurate.

I think it would be easy to implement this with [d3](https://d3js.org/). I may implement this at weekend, if I have time.

**Comment by MarineChap** [comment]
Your doc is very clear, at least for me! However, I did not have the time to work on it right now. That would be a relief for me if you do implement it this weekend but no pressure. :) 
Have a good weekend

**Comment by huww98** [comment]
The demo is at https://huww98.github.io/TimeChart/demo/plugins/events.html

**Comment by MarineChap** [comment]
That's awesome ! 
Working on the integration. I am not sure however to understand how to push new events in real-time. Is it possible with this implementation ? 

Thanks a lot for your work.

**Comment by MarineChap** [comment]
I am also very stuck with the new way to work with plugins ... Do you know what I am doing wrong ? I checked, everything has the right version.
```
🚨 Build failed.
@parcel/core: Failed to resolve 'timechart/core' from './src/plot.ts'
/home/chaputmarine/Documents/falcon-swr-client/client/src/plot.ts:9:23
   8 |  */
>  9 | import TimeChart from 'timechart/core';
>    |                       ^^^^^^^^^^^^^^^^
  10 | import { lineChart } from 'timechart/plugins/lineChart';
  11 | import { d3Axis } from 'timechart/plugins/d3Axis';
```

**Comment by huww98** [comment]
Sorry for that, this is not tested, and seems broken. I will investigate on this.

You may try `import TimeChart from 'timechart/dist/lib/core';` for now, as a workaround.

**Comment by huww98** [comment]
I updated the demo with a form to demonstrate adding new events. The import error should also be fixed in v1.0.0-beta.2, I've tested it with VS Code intellisense, `tsc`, webpack ts-loader.

Also, I did some rename from the last not released version. Please check the demo again.

**Comment by MarineChap** [comment]
Hello, Thanks a lot! I have been able to display my events, Look at this !! 

![image](https://user-images.githubusercontent.com/34722888/122359846-364bb380-cf56-11eb-8f03-3fc039fb9dae.png)


note: the bug with the path to import the timechart lib is still here so I am still using `import TimeChart from 'timechart/dist/lib/core';`

**Comment by huww98** [comment]
> note: the bug with the path to import the timechart lib is still here so I am still using import `TimeChart from 'timechart/dist/lib/core';`

Then maybe your toolchain is not new enough to support [package exports](https://webpack.js.org/guides/package-exports/)

**Comment by MarineChap** [comment]
Ok probably indeed something on my side. I will keep it like this for now as it is working. ^^
