### ISSUE TITLE
Traced don't appear when x is set to a time instead of a counter.

### ISSUE THREAD

**Issue by jumper385** [huww98/TimeChart#26]
![image](https://user-images.githubusercontent.com/17038915/125471223-2f0b64df-4669-44f2-8a6f-09032a6ebc11.png)

## Chart Setup
```javascript
let chart = new TimeChart(chartElement, {
        series: dataholder ,
        xRange: { min: 0, max: 30000 },
        realTime: true,
        zoom: {
            x: {
                autoRange: true,
            },
            y: {
                autoRange: true,
            }
        },
    });
```
## Sample data input

```javascript
let dataholder = [...{
   name:'category_name',
   data: [{x:1626186924936,y:6.94},{x: 1626186925193, y: 6.29}, {x: 1626186925448, y: 6.3} ...]
}]
```

Do you know what's going on here? could it be that the points on the line is just too small in the x-axis that WebGL just doesn't render it?

**Comment by huww98** [comment]
I have no idea. So long as x doesn't go backward, it should work. Could you also share the content of `dataholder` so that I can reproduce this?

**Comment by huww98** [comment]
Setting x to very large value is known to cause problems. Refer to the README:

> Due to the limitation of single-precision floating-point numbers, if the absolute value of x is large (e.g. Date.now()), you may need to use baseTime option (see below) to make the chart render properly.

You may try:
```javascript
let dataholder = [...{
   name:'category_name',
   data: [{x:0,y:6.94},{x: 257, y: 6.29}, {x: 512, y: 6.3} ...]
}]
let chart = new TimeChart(chartElement, {
        baseTime: 1626186924936,
        series: dataholder ,
        xRange: { min: 0, max: 30000 },
        realTime: true,
        zoom: {
            x: {
                autoRange: true,
            },
            y: {
                autoRange: true,
            }
        },
    });
```

**Comment by jumper385** [comment]
Ah! My bad - I misunderstood that. 
Thankyou @huww98 
Just want to say that this library is super fun to use btw 😊

**Comment by huww98** [comment]
Glad to hear that. You could also help me to improve the readme.

**Comment by jumper385** [comment]
I'll propose an update on the README for this issue - just to help clarify any future mistakes 😊
