### ISSUE TITLE
Problems with 1.0.0-beta

### ISSUE THREAD

**Issue by d-s-e** [huww98/TimeChart#29]
In my project I'm using TimeChart inside a Svelkte component built with Rollup.
I tried to use the new version of the library with not too much success.

Version **1.0.0-beta1** seems to work on Firefox and Chrome, but not on another Chromium-based browser or on Android:

        Uncaught SyntaxError: Unexpected token '.'

Version **1.0.0-beta2** doesn't even build:

        Error: 'default' is not exported by node_modules\timechart\dist\timechart.min.js

I also tried the example code, which builds, but leads to an error in the browser:

        Uncaught ReferenceError: TimeChart is not defined

Any ideas?

**Comment by huww98** [comment]
Will look at it later. I remember I have tested with Rollup. Maybe I should provide a known good Rollup config?

As for example code in this repo, they are continually built with GitHub actions. Last CI succeeded. And as you can see at https://huww98.github.io/TimeChart/demo/ . Currently they are working fine.

**Comment by d-s-e** [comment]
Maybe that could help.
I tried the example code also inside my component.

**Comment by d-s-e** [comment]
I think, I found the problem:
My application browser is based on Chromium 77, which is not supporting the ES11 features (like the optional chaining operator) you are using in your TypeScript code.
These are still present in the v1.x builds.
The release files for v0.5.2 are not containing those features, they must have been replaced in the transpile process.

**Comment by huww98** [comment]
That might be the case. I've increased the TS target version in v1-beta.

https://github.com/huww98/TimeChart/commit/4debe695330527c0b6084a7762aac2da883de0d5#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0

I'm thinking that the users can transpile it if needed. Is it hard to transpile this in your project?

**Comment by d-s-e** [comment]
TBH, I try to stay on my application level as far as possible, and not to mess around inside 3rd party packages and build options aside from my direct application settings, especially as I don't like this whole JavaScript/Node ecosystem anyway.
So I don't know if this will be hard or not. But maybe you can give me some helpful hints or links?

**Comment by huww98** [comment]
I'm not familiar with rollup either. I used to use vue-cli, which invokes webpack under the hook. It has a simple option [ transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies).

I will reconsider how to transpile my lib. Anyway I need to support including the js file directly from public CDN.

**Comment by d-s-e** [comment]
I finally fixed the problem by adding babel and making some small changes in my rollup config.
