### ISSUE TITLE
Demo doesn't work on Safari 13.1 on macOS Catalina and iOS 13.1

### ISSUE THREAD

**Issue by NeuronEye** [huww98/TimeChart#3]
[Error] Error: Unable to initialize WebGL. Your browser or machine may not support it.
	x (timechart.min.js:1:8925)
	(anonymous function) (timechart.min.js:1:21941)
	main (demo.js:7)
	Global Code (demo.js:1)

Safari 13.1 on macOS Catalina

<img width="870" alt="Screen Shot 2020-05-05 at 17 45 27" src="https://user-images.githubusercontent.com/65921/81053776-37f41c80-8ef8-11ea-9fea-c74162ca4b39.png">

It's working properly on Chrome 81.

**Comment by huww98** [comment]
Thank you for your interest. TimeChart uses WebGL2, and Safari [does not support that](https://caniuse.com/#feat=webgl2) currently. The error is expected. I have a plan to port this to support WebGL1. Stay tuned.

**Comment by huww98** [comment]
@NeuronEye I've added the support to WebGL1, and I've tested on iPhone 11. But I don't have a macOS device. Can you confirm this problem is fixed on Safari on macOS? Just open the [demo page](https://huww98.github.io/TimeChart/demo/) and it should work.

**Comment by NeuronEye** [comment]
@huww98 working well on Safari 13.1.1 on macOS Catalina 10.15.5

**Comment by huww98** [comment]
Thanks, I think this issue has been resolved.
