### ISSUE TITLE
how to export as png/jpg?

### ISSUE THREAD

**Issue by zillionare** [huww98/TimeChart#30]
the lib is great. One question though, I'd like use this lib to draw a graph and then export as png/jpg, how to achieve that?

**Comment by huww98** [comment]
I don't know. This can be quite complex, and I think is out of the scope of this lib.

For the WebGL part, canvas API should allow you to export it to image. But this lib also uses SVG and some HTML, which you need to deal with yourself. Maybe render them in another canvas. I believe there are plenty of libraries for this on GitHub.

**Comment by zillionare** [comment]
thanks. Maybe add this feature in future?
