### ISSUE TITLE
Zoom & Pause

### ISSUE THREAD

**Issue by chirag-lathiya-work** [huww98/TimeChart#37]
Hi @huww98 

As per my current requirements,
I need Zoom In & Zoom Out manually by clicking on the buttons (Right now it's possible thorough Mouse Scroll & Mouse Pan multi finger gesture)

I also noticed then when we zoom in the x axis, the live data stopped showing. (it stopped showing new data, after zoom In)

Your Stop is working, but when we required Resume/Start, that feature is not exist.

Let me know if that's possible.

Thank you for making amazing library.

**Comment by huww98** [comment]
Please use the "follow data" button to resume live data after pan/zoom.

**Comment by chirag-lathiya-work** [comment]
Okay thanks for letting me know that.

Is there any manual event possible for zoom/pan?

**Comment by huww98** [comment]
Yes. I quote my README:

> xRange / yRange ({min: number, max: number} or 'auto'): The range of x / y axes. Also use this to control pan / zoom programmatically.
