### ISSUE TITLE
Strange behavior on Ionic Vue, small chart

### ISSUE THREAD

**Issue by DrakoPOD** [huww98/TimeChart#38]
When the page is load, the chart display really small, in elements inspector some dimensions have 0, but they change on resize.

I need to resize the windows, calling `onResize` doesn't do anything. (I'm using the code example)
![image](https://user-images.githubusercontent.com/12172698/163430305-ba57a200-4ec0-4398-94d0-98626299a32d.png)

**Comment by huww98** [comment]
Sorry, I can only help if I can reproduce the issue. You should compare your CSS with the demo, and ensure the `<div>` is correctly sized before it is passed to TimeChart

**Comment by DrakoPOD** [comment]
I checked the div, it has 0 dimension, the only think that i was able to do was add a delay, is not practical, but works. Vue doesn't wait to the element to be fully rendered, even with `mounted()`.
