### ISSUE TITLE
Not appear line when series data shifted (npm version)

### ISSUE THREAD

**Issue by 01-jason** [huww98/TimeChart#41]
Hi, Thanks for works.

This is happened while using the 0.5.2 version of timechart in angular.

https://user-images.githubusercontent.com/14835736/165689474-93728d5e-0a9b-4cf7-8416-e8123480d0fa.mp4

vedio left side code(in vanila js - timechart.min.js)
<img width="350" alt="스크린샷 2022-04-28 오후 2 54 50" src="https://user-images.githubusercontent.com/14835736/165689658-2774717e-0996-4002-af5e-b75455f2a485.png">

vedio right side code(in angular - npm install timechart)
<img width="373" alt="스크린샷 2022-04-28 오후 2 54 56" src="https://user-images.githubusercontent.com/14835736/165689731-e310a481-d56e-457a-b642-1dad24edc444.png">

Is it that npm timechart version has not been updated?

**Comment by huww98** [comment]
Try `npm i timechart@beta`

I need some more time to finalize the API design.
