### ISSUE TITLE
interpolation line

### ISSUE THREAD

**Issue by fast0490f** [huww98/TimeChart#51]
Hi, how hard is it to do?

**Comment by fast0490f** [comment]
https://www.chartjs.org/docs/next/samples/line/interpolation.html

**Comment by huww98** [comment]
I would consider this out of the scope of this project. Drawing curves with WebGL is highly inefficient. chartjs uses canvas 2D, which supports curves natively.

**Comment by huww98** [comment]
WebGL draws triangles, you can imagine how many triangles are needed to form a visually smooth curve.

**Comment by fast0490f** [comment]
@huww98 ok, now I understand what the problem is. As I understand it, I only have points, lines and triangles at my disposal ?

**Comment by huww98** [comment]
basically, you only have triangles. Although WebGL is capable of drawing points and lines, you cannot control the point size or line width. So I'm not using them in this project. All lines drawn by `lineChart.ts` are composed of triangles.
