### ISSUE TITLE
Add optional Formatter function for x-value

### ISSUE THREAD

**Issue by leonard84** [huww98/TimeChart#55]
When using `baseTime` and a time scale, the x-axis gets nicely formatted, but the tooltip still shows the raw value for the x-axis. It would be nice if it was possible to pass a formatter function, so that you could see the actual date and time.

**Comment by huww98** [comment]
6c5d9ec578d1161f2ec8e026ccf1501242960180

**Comment by leonard84** [comment]
thanks

**Comment by leonard84** [comment]
How can I prevent the xTooltip from being clipped? I need to include the date portion as well and this causes the text to be elided. Same for the other labels under `X`.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1151511/194910367-54e1961a-0ccf-428a-8f99-361d919a7a8c.png">

**Comment by huww98** [comment]
I don't have a good solution. You may inject some CSS style into the chart with JS. This seems hacky but should work.

**Comment by huww98** [comment]
for example:
```JavaScript
chart.shadowRoot.querySelector('chart-tooltip').shadowRoot.querySelector('style').innerText += `.value { min-width: 200px; max-width: 200px }`
```

**Comment by leonard84** [comment]
Can't you use the domain values and the max label length to dynamically calculate the needed tooltip max-size?

**Comment by huww98** [comment]
For labels, it is already dynamically expanding to 100px, maybe you just need a larger `max-size`?

For domain value, since the length of the formatted string may change, I don't want the size of tooltip to change constantly.

**Comment by leonard84** [comment]
We could reduce the flatter, by only ever growing the box (up to a configurable maximum) if we see a larger value.

**Comment by huww98** [comment]
Yes, but that could be difficult to implement.

**Comment by leonard84** [comment]
Could you offer configurable sizes for the tooltip then to get rid of the workaround with shadowRoot?

**Comment by huww98** [comment]
I think the ::part CSS pseudo-element can be used. I will look at this next weekend.

**Comment by huww98** [comment]
> I think the ::part CSS pseudo-element can be used.

This is more difficult than I thought. ::part cannot select elements in the nested shadow root.

Maybe I should adopt a more Web Component like interface. But I would leave the interface changes to future v2.0.

**Comment by leonard84** [comment]
I was thinking on making parts the of the style content configurable, you already create it via js in the tooltip plugin anyway, so it should be possible to use parameters for the css.
