### ISSUE TITLE
Chart rendering broken on Mac

### ISSUE THREAD

**Issue by leonard84** [huww98/TimeChart#57]
The changes in #53 seems to have broken rendering on mac for FF and Chrome.

I tested it with the latest FF 105.0.3 and Chrome 106.0.5249.103 on Mac and it doesn't show up.
It works with Safari 16.0 (17614.1.25.9.10, 17614) on Mac, or FF on windows.

Chrome `chrome://gpu` report for mac says WebGL2 is enabled.
```
Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Direct Rendering Display Compositor: Disabled
Compositing: Hardware accelerated
Metal: Disabled
Multiple Raster Threads: Enabled
OpenGL: Enabled
Rasterization: Hardware accelerated
Raw Draw: Disabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
WebGPU: Disabled
```

I can also see the spinning cube in a webgl 2 test page https://get.webgl.org/webgl2/

**Comment by leonard84** [comment]
Here is an example, it does render the current value point though.
## FF
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/1151511/194837258-4b91d2ae-88b5-4eb2-9d1d-a6dd15374c2e.png">

## Chrome
<img width="959" alt="image" src="https://user-images.githubusercontent.com/1151511/194837400-9384ef41-7391-4297-9921-3acfe2060ba5.png">

**Comment by huww98** [comment]
Could you please share the error message from console? I don't have Mac to reproduce this issue

**Comment by leonard84** [comment]
There is only a warning

FF: `WebGL warning: drawArraysInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.`

Chrome: `line_style.html:1 [.WebGL-0x12400dd9c00] GL_INVALID_OPERATION: It is undefined behaviour to use a uniform buffer that is too small.`

**Comment by huww98** [comment]
OK, I think I know the problem. Will try to fix it soon.

**Comment by huww98** [comment]
I've just pushed a new version to master. Please verify whether it fixes this issue.

**Comment by huww98** [comment]
> it does render the current value point though

Because that small circle is rendered by SVG. The lines are rendered by WebGL

**Comment by leonard84** [comment]
The fix works, thanks.
