### ISSUE TITLE
Line doesn't render

### ISSUE THREAD

**Issue by zadeviggers** [huww98/TimeChart#65]
When using beta 9, lines won't render. This was fixed in https://github.com/huww98/TimeChart/commit/fabd3f03531b3b3983bdb2f4858fbd7429d47b75, but the fix was never published.
A temporary solution is to change package.json to download the library directly from Git Hub.
```diff
	"dependencies": {
-		"timechart": "^1.0.0-beta.9"
+		"timechart": "github:huww98/TimeChart"
	}
```

**Comment by huww98** [comment]
1.0.0-beta.10 published, along with some dependency update. Thanks.
