### ISSUE TITLE
Adding vertical lines

### ISSUE THREAD

**Issue by sleighsoft** [huww98/TimeChart#7]
Is it possible to add vertical lines to the chart on click? If not, how difficult would it be to add this functionality?

**Comment by huww98** [comment]
This can be easy to implement, it should look like the [crosshair](https://github.com/huww98/TimeChart/blob/master/src/crosshair.ts).

I'm planning for a plugin mechanism so that people can add functionality like this without modifying the code from this library.

**Comment by huww98** [comment]
I've made a demo that adds vertical lines programmatically. https://huww98.github.io/TimeChart/demo/plugins/events.html

As for adding on click, I don't want to include it in this library, because the UI varies a lot depending on the use case.
