### ISSUE TITLE
Question, render to texture 

### ISSUE THREAD

**Issue by temaivanoff** [huww98/TimeChart#70]
Hi, I'm studying the code and see the rendering is happening through the texture. Why ? what's the secret? productivity? why not attribute?

**Comment by huww98** [comment]
I used to use attributes to store datapoints. But every vertex can only access its own attribute, not the adjacent ones. That results in a lot of duplicated data.

See https://github.com/huww98/TimeChart/commit/a4cfbfa1cfa9c3067fe1b8937278bace65e203fa for the transition from attribute to texture.

**Comment by huww98** [comment]
In summary, I use texture in order to:
- cut down GPU memory usage
- support dynamic switch of chart type
