### ISSUE TITLE
After resizing the chart, a method is needed to automatically refill the chart viewport.

### ISSUE THREAD

**Issue by yueduz** [huww98/TimeChart#83]

**Comment by huww98** [comment]
Are you looking for `chart.onResize()` ?

**Comment by yueduz** [comment]
I used a translation tool, so there might be inaccuracies. What I meant
was, after zooming in or out on the x and y axes of the chart, is there a
way to automatically make the chart content fill the chart viewport?

文心大模型3.5生成

胡玮文 ***@***.***> 于 2024年11月4日周一 20:50写道：

**Comment by huww98** [comment]
You may set xRange / yRange to 'auto'.

BTW, 我是中国人。

**Comment by yueduz** [comment]
我要的就是这个,谢谢!
