### ISSUE TITLE
Autorange on y does not resume after stopping or panning

### ISSUE THREAD

**Issue by tomy983** [huww98/TimeChart#84]
Hi, I'm testing the [dynamic_data.html](https://github.com/huww98/TimeChart/blob/master/demo/dynamic_data.html) demo.
I've replaced the sin function with an increasing number, pressed the stop button (pan or mouse wheel has the same effect).
After pressing the `Follow data` button the autoRange on y axis does not resume. 

I've tried adding `chart.options.zoom.y.autoRange = true;` on click function of `follow-btn` but had no success.

I've also tried to splice the data from the beginning and notice that the y axis will not rescale to match the remaining data. 

Thank you for your great work!

**Comment by huww98** [comment]
Have you tried `chart.options.yRange = "auto"`?

**Comment by huww98** [comment]
> I've also tried to splice the data from the beginning and notice that the y axis will not rescale to match the remaining data.

This is by-design. the auto range will only expand but not shrink. Because when the dataset is very large, there is no easy way to rescale without rescan the whole dataset.

**Comment by tomy983** [comment]
> Have you tried `chart.options.yRange = "auto"`?

I've tried to add it to the` document.getElementById('follow-btn').addEventListener('click', function ()` and it works as expected, thank you. 

I got confused because of the way the autorange is set in the example and I thought I had to call it that way...

Thank you

**Comment by huww98** [comment]
`zoom.y.autoRange` determines the boundary that you can zoom/pan interactively within it. `yRange` determines the range actually shown on the screen.
